server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/testingdb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Akhi.sai1310@
#spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=validate
resilience4j.circuitbreaker.instances.userProfileService.register-health-indicator=true
resilience4j.circuitbreaker.instances.userProfileService.sliding-window-size=10
resilience4j.circuitbreaker.instances.userProfileService.failure-rate-threshold=90
resilience4j.circuitbreaker.instances.userProfileService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.userProfileService.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.userProfileService.permitted-number-of-calls-in-half-open-state=3

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
